###
GET http://localhost:3000

###
POST http://localhost:3000/register
Content-Type: application/json

{
"fullName": "Juozas",
"email": "juozas1@gmail.com",
"password": "master"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
"fullName": "Juozas",
"email": "juozas1@gmail.com",
"password": "master"
}

###
POST http://localhost:3000/accounts
Content-Type: application/json

{
"user_id": 3,
"group_id": 3
}