###
GET http://localhost:3000

###
POST http://localhost:3000/register
Content-Type: application/json

{
"fullName": "Tomas",
"email": "tomas1@gmail.com",
"password": "master"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
"fullName": "Tomas",
"email": "tomas1@gmail.com",
"password": "master"
}