###
GET http://localhost:3000

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
"fullName": "Vardenis Pavardenis",
"email": "vartotojas1@gmail.com",
"password": "master"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
"fullName": "Vardenis Pavardenis",
"email": "vartotojas1@gmail.com",
"password": "master"
}

###
POST http://localhost:3000/api/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJpYXQiOjE2NTM2NDAxODEsImV4cCI6MTY1MzY0Mzc4MX0.gygTYtNHx2mQiPTdh17Fs2KukEASulftmrxTX2CYWaU

{
"group_id": 1
}

###
GET http://localhost:3000/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJpYXQiOjE2NTM2NDAxODEsImV4cCI6MTY1MzY0Mzc4MX0.gygTYtNHx2mQiPTdh17Fs2KukEASulftmrxTX2CYWaU

###
GET http://localhost:3000/api/bills/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJpYXQiOjE2NTM2NDAxODEsImV4cCI6MTY1MzY0Mzc4MX0.gygTYtNHx2mQiPTdh17Fs2KukEASulftmrxTX2CYWaU

###
POST http://localhost:3000/api/bills?group_id=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJpYXQiOjE2NTM2NDAxODEsImV4cCI6MTY1MzY0Mzc4MX0.gygTYtNHx2mQiPTdh17Fs2KukEASulftmrxTX2CYWaU

{
"group_id": 1,
"amount": 150,
"description": "Trip to spain"
}
